// One-time setup script. Run with:
//   node --env-file=.env scripts/seed.mjs
//
// - Creates (or updates the password of) the admin login from ADMIN_EMAIL / ADMIN_PASSWORD.
// - Imports the original 19-car inventory into MongoDB, but only if the `cars`
//   collection is currently empty (safe to re-run after that).
import { MongoClient } from 'mongodb'
import bcrypt from 'bcryptjs'

const DEFAULT_CHECKLIST = ['Full inspection', 'Engine diagnostic', 'Brake check', 'Interior clean']
const DEFAULT_SERVICES = [
  { label: 'Full diagnostic scan', amount: 'Included', percent: 18 },
  { label: 'Roadworthiness prep', amount: 'Included', percent: 24 },
  { label: 'Import clearance support', amount: 'Included', percent: 31 },
  { label: 'Delivery to Takoradi', amount: 'Included', percent: 14 },
]

const CARS = [
  { category: 'pickup', meta: 'Pickup · GWM', name: 'GWM Poer Cannon', shortName: 'Poer Cannon', year: '2023', edition: 'Black Double Cab', sku: '#WM-POER-001', origin: 'China', transmission: 'Automatic', drive: '4x4', seats: '5 Seats', fuel: 'Petrol', power: 'Premium Pickup', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'Glossy black GWM Poer double-cab with sports bar and alloy wheels, rugged, stylish, and ready for work or family use.', image: '/b6bde9b4-b9a0-4b73-90d9-d32411e7c729.jpg', gallery: ['/b6bde9b4-b9a0-4b73-90d9-d32411e7c729.jpg', '/54ba6b2b-e137-4f68-b635-7508a0b5abd5.jpg', '/693b9092-60cc-448c-87eb-174840743404.jpg'], tags: ['4x4', 'China Import', 'Double Cab', 'Petrol'], condition: { restored: 20, inspected: 55, original: 25 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'pickup', meta: 'Pickup · Ford', name: 'Ford Ranger', shortName: 'Ranger', year: '2022', edition: 'Off-Road Edition', sku: '#WM-RNG-002', origin: 'America', transmission: 'Automatic', drive: '4x4', seats: '5 Seats', fuel: 'Petrol', power: 'Off-Road Ready', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'Aggressive black Ford Ranger with bold grille, snorkel, and all-terrain setup, built for Ghana’s toughest roads.', image: '/5f3b8ce5-c56e-4c70-bd3c-6b82c63f41d6.jpg', gallery: ['/5f3b8ce5-c56e-4c70-bd3c-6b82c63f41d6.jpg', '/818a06be-7b07-403e-809a-a38228abfa9f.jpg', '/d8fa383c-5db1-43db-a8f7-8757bb68a026.jpg'], tags: ['4x4', 'America Import', 'Snorkel', 'Petrol'], condition: { restored: 18, inspected: 58, original: 24 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'pickup', meta: 'Pickup · GWM', name: 'GWM Poer Off-Road', shortName: 'Poer Red', year: '2023', edition: 'Red Snorkel Edition', sku: '#WM-POER-003', origin: 'China', transmission: 'Automatic', drive: '4x4', seats: '5 Seats', fuel: 'Petrol', power: 'Off-Road Spec', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'Striking red GWM Poer with snorkel, black flares, and sports bar, a standout pickup for adventure and utility.', image: '/43067f4f-54d3-4156-a097-6de6cb61a56d.jpg', gallery: ['/43067f4f-54d3-4156-a097-6de6cb61a56d.jpg'], tags: ['4x4', 'China Import', 'Snorkel', 'Double Cab', 'Petrol'], condition: { restored: 22, inspected: 50, original: 28 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'pickup', meta: 'Pickup · GWM', name: 'GWM Poer 4x4', shortName: 'Poer Blue', year: '2023', edition: 'Blue Chrome Edition', sku: '#WM-POER-004', origin: 'China', transmission: 'Automatic', drive: '4x4', seats: '5 Seats', fuel: 'Petrol', power: 'Premium Cabin', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'Royal blue GWM Poer 4x4 with chrome grille, bed rack, and premium brown/cream quilted interior.', image: '/b8a6241f-c1b2-4dfc-92c9-8047f3f0cafc.jpg', gallery: ['/b8a6241f-c1b2-4dfc-92c9-8047f3f0cafc.jpg', '/5f595e84-d4b2-42bb-a0b5-2d03862f192b.jpg', '/63305be3-9062-48a3-b3c1-eb866c39455a.jpg', '/3658d2fb-40f3-4cec-b078-3f866dd3aa66.jpg'], tags: ['4x4', 'China Import', 'Premium Interior', 'Petrol'], condition: { restored: 15, inspected: 60, original: 25 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'pickup', meta: 'Pickup · GWM', name: 'GWM Poer Bull Bar', shortName: 'Poer Bronze', year: '2022', edition: 'Bronze Utility', sku: '#WM-POER-005', origin: 'China', transmission: 'Automatic', drive: '4x4', seats: '5 Seats', fuel: 'Petrol', power: 'Work Ready', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'Bronze metallic GWM Poer with heavy-duty bull bar and LED pods, tough looks for business and transport.', image: '/b070a583-6ec1-4bdd-a409-618eb60f1094.jpg', gallery: ['/b070a583-6ec1-4bdd-a409-618eb60f1094.jpg', '/415c4e6d-5853-4732-a002-de7b476d26e0.jpg'], tags: ['4x4', 'China Import', 'Bull Bar', 'Petrol'], condition: { restored: 25, inspected: 48, original: 27 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'suv', meta: 'SUV · Toyota', name: 'Toyota Corolla Cross', shortName: 'Corolla Cross', year: '2024', edition: 'White Compact', sku: '#WM-CCX-006', origin: 'Japan', transmission: 'Automatic', drive: 'FWD', seats: '5 Seats', fuel: 'Petrol', power: 'City Friendly', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'White Toyota Corolla Cross 2024 compact SUV, efficient, stylish, and ideal for city driving in Ghana.', image: '/8c85168a-012a-4051-a772-f3c71abc0a77.jpg', gallery: ['/8c85168a-012a-4051-a772-f3c71abc0a77.jpg', '/6526ec85-6c2c-419a-b768-35ea8ed35859.jpg', '/6f1df778-d632-430c-ac7f-2a54f26779e7.jpg', '/hh.jpg'], tags: ['SUV', 'Japan Import', 'Compact', 'Petrol', '2024'], condition: { restored: 12, inspected: 62, original: 26 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'sedan', meta: 'Sedan · Toyota', name: 'Toyota Vios', shortName: 'Vios', year: '2021', edition: 'White Sedan', sku: '#WM-VIO-007', origin: 'Japan', transmission: 'Automatic', drive: 'FWD', seats: '5 Seats', fuel: 'Petrol', power: 'Daily Drive', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'Reliable white Toyota sedan, comfortable, fuel-efficient, and perfect for everyday personal use.', image: '/b987da2a-e94c-400e-aaa0-51b7b32ef66b.jpg', gallery: ['/b987da2a-e94c-400e-aaa0-51b7b32ef66b.jpg', '/4ff32133-5011-48bc-963e-0e1363438095.jpg'], tags: ['Sedan', 'Japan Import', 'Automatic', 'Petrol'], condition: { restored: 20, inspected: 52, original: 28 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'suv', meta: 'SUV · Toyota', name: 'Toyota RAV4', shortName: 'RAV4', year: '2022', edition: 'White Adventure', sku: '#WM-RAV-008', origin: 'Japan', transmission: 'Automatic', drive: 'AWD', seats: '5 Seats', fuel: 'Petrol', power: 'Family SUV', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'Fifth-generation Toyota RAV4 in white, spacious, modern, and trusted for family and highway travel.', image: '/acd02303-de0f-4014-b142-461a2ac43ac4.jpg', gallery: ['/acd02303-de0f-4014-b142-461a2ac43ac4.jpg', '/5cb664cf-7729-4527-ae98-72af6a109d87.jpg', '/41d0d979-cd65-46e4-89e4-869820932368.jpg'], tags: ['SUV', 'Japan Import', 'AWD', 'Petrol'], condition: { restored: 14, inspected: 58, original: 28 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'suv', meta: 'SUV · Changan', name: 'Changan UNI-T', shortName: 'UNI-T', year: '2023', edition: 'Red Sport', sku: '#WM-UNI-009', origin: 'China', transmission: 'Automatic', drive: 'FWD', seats: '5 Seats', fuel: 'Petrol', power: 'Modern Crossover', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'Metallic red Changan UNI-T with futuristic grille and red-stitched cabin, bold style for the city.', image: '/426076a6-a57b-4b50-85bc-36fe5b046bf5.jpg', gallery: ['/426076a6-a57b-4b50-85bc-36fe5b046bf5.jpg', '/07df2206-6fc8-49cb-a2a1-53b9f086895a.jpg', '/e7602ca6-61d7-4a7b-9cad-943528262073.jpg'], tags: ['SUV', 'China Import', 'Sport', 'Petrol'], condition: { restored: 10, inspected: 65, original: 25 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'suv', meta: 'SUV · Jetour', name: 'Jetour T2 Traveler', shortName: 'Jetour T2', year: '2023', edition: 'Grey Adventure', sku: '#WM-JT2-010', origin: 'China', transmission: 'Automatic', drive: '4x4', seats: '5 Seats', fuel: 'Petrol', power: 'Off-Road SUV', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'Boxy Jetour T2 Traveler with roof box, side ladder, and spare cover, adventure-ready for West Africa.', image: '/4c424dee-367a-419c-a349-175e4092f811.jpg', gallery: ['/4c424dee-367a-419c-a349-175e4092f811.jpg', '/cee75be6-9dce-430d-8556-91a739491023.jpg'], tags: ['SUV', 'China Import', 'Adventure', '4x4'], condition: { restored: 16, inspected: 54, original: 30 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'suv', meta: 'SUV · GWM', name: 'GWM Tank 300', shortName: 'Tank 300', year: '2023', edition: 'Silver Off-Road', sku: '#WM-TNK-011', origin: 'China', transmission: 'Automatic', drive: '4x4', seats: '5 Seats', fuel: 'Petrol', power: 'Rugged SUV', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'Silver GWM Tank 300 with rear spare cover and bold off-road stance, serious capability with premium presence.', image: '/70d3244f-9bc4-41e0-80de-a023dceb2d99.jpg', gallery: ['/70d3244f-9bc4-41e0-80de-a023dceb2d99.jpg', '/b5a8afcd-8e0c-46ac-8de7-51bd80b60aed.jpg'], tags: ['SUV', 'China Import', '4x4', 'Off-Road'], condition: { restored: 18, inspected: 56, original: 26 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'suv', meta: 'SUV · Jetour', name: 'Jetour Dashing', shortName: 'Dashing', year: '2023', edition: 'Light Grey', sku: '#WM-JDS-012', origin: 'China', transmission: 'Automatic', drive: 'FWD', seats: '5 Seats', fuel: 'Petrol', power: 'Family Crossover', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'Light grey Jetour Dashing with panoramic roof and modern styling, comfortable crossover for daily driving.', image: '/b7c9c97f-6a00-4c05-96c5-9a3c300d0eae.jpg', gallery: ['/b7c9c97f-6a00-4c05-96c5-9a3c300d0eae.jpg', '/0efea8c3-e88f-4336-9b02-776e682bafbb.jpg'], tags: ['SUV', 'China Import', 'Panoramic', 'Petrol'], condition: { restored: 12, inspected: 60, original: 28 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'suv', meta: 'SUV · Changan', name: 'Changan CS Series', shortName: 'Changan SUV', year: '2022', edition: 'Black Premium', sku: '#WM-CHS-013', origin: 'China', transmission: 'Automatic', drive: 'FWD', seats: '5 Seats', fuel: 'Petrol', power: 'Premium Cabin', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'Glossy black Changan SUV with honeycomb grille and diamond-stitched interior, refined and ready to drive.', image: '/6e0c10ae-fa19-4738-b63e-835a8324334b.jpg', gallery: ['/6e0c10ae-fa19-4738-b63e-835a8324334b.jpg', '/4359e605-65a4-46f5-9997-24b205045dc5.jpg'], tags: ['SUV', 'China Import', 'Premium', 'Petrol'], condition: { restored: 15, inspected: 57, original: 28 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'suv', meta: 'SUV · Haval', name: 'Haval H6 GT', shortName: 'H6 GT', year: '2022', edition: 'Black Coupe', sku: '#WM-H6G-014', origin: 'China', transmission: 'Automatic', drive: 'FWD', seats: '5 Seats', fuel: 'Petrol', power: 'Sport Crossover', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'Sleek black coupe-style Haval crossover with tinted glass and sporty lines, modern premium SUV styling.', image: '/a85eb977-ddc2-4986-9096-ec5dd42ea492.jpg', gallery: ['/a85eb977-ddc2-4986-9096-ec5dd42ea492.jpg', '/811cca07-a850-407a-a292-dff7245babab.jpg'], tags: ['SUV', 'China Import', 'Sport', 'Petrol'], condition: { restored: 14, inspected: 59, original: 27 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'suv', meta: 'SUV · Jetour', name: 'Jetour X70', shortName: 'X70', year: '2022', edition: 'White Family', sku: '#WM-JX7-015', origin: 'China', transmission: 'Automatic', drive: 'FWD', seats: '7 Seats', fuel: 'Petrol', power: 'Family SUV', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'White Jetour X70 family SUV with chrome grille and connected rear light, spacious option for Ghana families.', image: '/6bb8d20d-e0bd-48c9-a093-7978f5469f46.jpg', gallery: ['/6bb8d20d-e0bd-48c9-a093-7978f5469f46.jpg', '/1b92b06d-6746-4bfd-a686-bef7b506d2f7.jpg', '/e7d821ec-7371-4786-9f88-a16db81e8e53.jpg'], tags: ['SUV', 'China Import', 'Family', 'Petrol'], condition: { restored: 17, inspected: 53, original: 30 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'sedan', meta: 'Sedan · Toyota', name: 'Toyota Levin Hybrid', shortName: 'Levin Hybrid', year: '2023', edition: 'White Hybrid', sku: '#WM-LVN-016', origin: 'China', transmission: 'Automatic', drive: 'FWD', seats: '5 Seats', fuel: 'Hybrid', power: 'Fuel Efficient', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'White Toyota Levin Hybrid sedan, modern, efficient, and ideal for city and highway driving across Ghana.', image: '/4326cd89-cc68-4d5f-aeff-563d52fc4b64.jpg', gallery: ['/4326cd89-cc68-4d5f-aeff-563d52fc4b64.jpg', '/ff84d59b-0385-4a51-83f1-a4864e6b8c53.jpg', '/f1dc6a98-8191-4417-bbf6-2e2278a511a2.jpg'], tags: ['Sedan', 'Hybrid', 'China Import', 'Automatic'], condition: { restored: 8, inspected: 68, original: 24 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'commercial', meta: 'Commercial · Toyota', name: 'Toyota Alphard', shortName: 'Alphard', year: '2018', edition: 'White MPV', sku: '#WM-ALP-017', origin: 'Japan', transmission: 'Automatic', drive: 'FWD', seats: '7 Seats', fuel: 'Petrol', power: 'Premium MPV', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'Spacious white Toyota Alphard MPV, comfortable people-mover for family, business, and passenger transport.', image: '/c72b40f3-bf0c-49f3-864c-611be2abaa37.jpg', gallery: ['/c72b40f3-bf0c-49f3-864c-611be2abaa37.jpg'], tags: ['MPV', 'Japan Import', '7 Seats', 'Commercial'], condition: { restored: 30, inspected: 45, original: 25 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'commercial', meta: 'Commercial · Toyota', name: 'Toyota Voxy', shortName: 'Voxy', year: '2018', edition: 'White ZS MPV', sku: '#WM-VOX-018', origin: 'Japan', transmission: 'Automatic', drive: 'FWD', seats: '7 Seats', fuel: 'Petrol', power: 'Family MPV', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'White Toyota Voxy MPV with sliding doors and spacious cabin, ideal for family, church, and passenger transport.', image: '/be81f560-1f41-4296-b666-9594eb110e05.jpg', gallery: ['/be81f560-1f41-4296-b666-9594eb110e05.jpg', '/df0bcf45-9f57-4f41-b124-4a066739bf34.jpg', '/06a2ba01-9bcd-443a-a1c3-db05a34f6fce.jpg', '/9ffdb2dc-1a13-468b-8c2f-6176c8dd098b.jpg'], tags: ['MPV', 'Japan Import', '7 Seats', 'Petrol'], condition: { restored: 22, inspected: 55, original: 23 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
  { category: 'suv', meta: 'SUV · Samsung', name: 'Samsung QM6', shortName: 'QM6', year: '2020', edition: 'Grey Premium', sku: '#WM-QM6-019', origin: 'Korea', transmission: 'Automatic', drive: 'AWD', seats: '5 Seats', fuel: 'Petrol', power: 'Family SUV', location: 'Takoradi', priceLabel: 'Enquire for price', summary: 'Metallic grey Samsung QM6 SUV with chrome grille, roof rails, and side steps, a comfortable crossover for Ghana roads.', image: '/df950829-5f55-4548-8399-bbff8e62490d.jpg', gallery: ['/df950829-5f55-4548-8399-bbff8e62490d.jpg', '/d0ed9ac0-2c72-4d2a-8206-8fc6634b589d.jpg', '/bdf5540d-8b1e-4426-aa97-71e01517864a.jpg', '/c13b5fee-e415-43a8-a76f-b5b38415c191.jpg'], tags: ['SUV', 'Korea Import', 'AWD', 'Petrol'], condition: { restored: 18, inspected: 58, original: 24 }, estimate: 'Enquire', checklist: DEFAULT_CHECKLIST, services: DEFAULT_SERVICES },
]

async function main() {
  const uri = process.env.MONGODB_URI
  if (!uri) throw new Error('MONGODB_URI is not set (pass it via --env-file=.env)')

  const client = new MongoClient(uri)
  await client.connect()
  const db = client.db()

  const adminEmail = (process.env.ADMIN_EMAIL || '').toLowerCase().trim()
  const adminPassword = process.env.ADMIN_PASSWORD
  if (adminEmail && adminPassword) {
    const passwordHash = await bcrypt.hash(adminPassword, 10)
    await db
      .collection('admins')
      .updateOne({ email: adminEmail }, { $set: { email: adminEmail, passwordHash } }, { upsert: true })
    console.log(`Admin login ready: ${adminEmail}`)
  } else {
    console.log('Skipped admin user (set ADMIN_EMAIL and ADMIN_PASSWORD in .env to create one)')
  }

  const carsCollection = db.collection('cars')
  const existing = await carsCollection.countDocuments()
  if (existing > 0) {
    console.log(`Skipped car import — "cars" collection already has ${existing} document(s).`)
  } else {
    const now = new Date()
    const docs = CARS.map((car) => ({ ...car, createdAt: now, updatedAt: now }))
    const result = await carsCollection.insertMany(docs)
    console.log(`Imported ${result.insertedCount} cars.`)
  }

  await client.close()
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
