export const CONTACT = {
  phone: '+233 202914993',
  phoneHref: 'tel:+233202914993',
  email: 'westlifemotors@gmail.com',
  emailHref: 'mailto:westlifemotors@gmail.com',
  address: 'Opposite Apowa Police Station, Takoradi',
  hours: 'Mon-Sat: 8:00 - 18:00',
  markets: ['Ghana', "Côte d'Ivoire"],
}

export const NAV_LINKS = [
  { href: '/#home', label: 'Home' },
  { href: '/#inventory', label: 'Inventory' },
  { href: '/#types', label: 'Vehicles' },
  { href: '/#about', label: 'About' },
  { href: '/#why', label: 'Why Us' },
  { href: '/#contact', label: 'Contact' },
]

export const HERO_SLIDES = [
  'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=2000&q=80',
  'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=2000&q=80',
  'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=2000&q=80',
]

export const BRANDS = [
  { name: 'Toyota', logo: '/brands/toyota.svg' },
  { name: 'Ford', logo: '/brands/ford.svg' },
  { name: 'GWM', logo: '/brands/gwm.svg' },
  { name: 'Haval', logo: '/brands/haval.svg' },
  { name: 'Changan', logo: '/brands/changan.svg' },
  { name: 'Jetour', logo: '/brands/jetour.svg' },
]

export const TRENDING = [
  {
    title: 'Sedans for city driving',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=800&q=80',
  },
  {
    title: 'SUVs for every terrain',
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=80',
  },
  {
    title: 'Pickups built for work',
    image: 'https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=800&q=80',
  },
  {
    title: 'Trucks for heavy duty',
    image: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=800&q=80',
  },
  {
    title: 'Commercial vans & buses',
    image: '/c72b40f3-bf0c-49f3-864c-611be2abaa37.jpg',
  },
]

export const VEHICLE_TYPES = [
  {
    name: 'Sedan',
    tag: 'Comfort',
    description: 'Stylish cars ideal for city driving and personal use.',
    image: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=700&q=80',
  },
  {
    name: 'SUV',
    tag: 'Adventure',
    description: 'Rugged, spacious vehicles for urban and off-road travel.',
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=700&q=80',
  },
  {
    name: 'Pickup',
    tag: 'Utility',
    description: 'Durable and versatile for business and everyday work.',
    image: 'https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=700&q=80',
  },
  {
    name: 'Truck',
    tag: 'Heavy-duty',
    description: 'Built for logistics, construction, and industrial needs.',
    image: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=700&q=80',
  },
  {
    name: 'Commercial',
    tag: 'Business',
    description: 'Vans and buses for passenger or cargo transport.',
    image: '/c72b40f3-bf0c-49f3-864c-611be2abaa37.jpg',
  },
]

export const WHY_US = [
  {
    title: 'Global Partnerships',
    text: 'Trusted suppliers across America, Europe, Japan, and China, so you get quality vehicles with confidence.',
    icon: 'globe',
  },
  {
    title: 'Transparent Practices',
    text: 'Clear pricing, honest condition reports, and business practices built on integrity from day one.',
    icon: 'shield',
  },
  {
    title: 'Reliable Logistics',
    text: 'Efficient import and distribution from our Takoradi base across Ghana and Côte d’Ivoire.',
    icon: 'truck',
  },
  {
    title: 'Customer First',
    text: 'Personal guidance to match every client with the right vehicle for their lifestyle and budget.',
    icon: 'heart',
  },
]

export const FAQS = [
  {
    q: 'Do you import cars from America, Europe, Japan, and China?',
    a: 'Yes. Westlife Motors specializes in importing quality vehicles from America, Europe, Japan, and China for customers across Ghana and Côte d’Ivoire.',
  },
  {
    q: 'Where is your showroom located?',
    a: 'We are based opposite Apowa Police Station in Takoradi. Visit us during business hours or book a viewing ahead of time.',
  },
  {
    q: 'Can I reserve or view a vehicle before buying?',
    a: 'Absolutely. Contact us by phone or email to book a viewing. Our team will walk you through the vehicle, condition, and options.',
  },
  {
    q: 'Do you deliver outside Takoradi?',
    a: 'Yes. We support delivery and distribution across Ghana and into Côte d’Ivoire. Ask us about timing and logistics for your location.',
  },
  {
    q: 'Are prices listed online?',
    a: 'Pricing depends on the vehicle, specs, and import details. Contact us for a clear quote with no hidden surprises.',
  },
]

const DEFAULT_CHECKLIST = ['Full inspection', 'Engine diagnostic', 'Brake check', 'Interior clean']
const DEFAULT_SERVICES = [
  { label: 'Full diagnostic scan', amount: 'Included', percent: 18 },
  { label: 'Roadworthiness prep', amount: 'Included', percent: 24 },
  { label: 'Import clearance support', amount: 'Included', percent: 31 },
  { label: 'Delivery to Takoradi', amount: 'Included', percent: 14 },
]

export const CARS = [
  {
    id: 1,
    category: 'pickup',
    meta: 'Pickup · GWM',
    name: 'GWM Poer Cannon',
    shortName: 'Poer Cannon',
    year: '2023',
    edition: 'Black Double Cab',
    sku: '#WM-POER-001',
    origin: 'China',
    transmission: 'Automatic',
    drive: '4x4',
    seats: '5 Seats',
    fuel: 'Petrol',
    power: 'Premium Pickup',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'Glossy black GWM Poer double-cab with sports bar and alloy wheels, rugged, stylish, and ready for work or family use.',
    image: '/b6bde9b4-b9a0-4b73-90d9-d32411e7c729.jpg',
    gallery: [
      '/b6bde9b4-b9a0-4b73-90d9-d32411e7c729.jpg',
      '/54ba6b2b-e137-4f68-b635-7508a0b5abd5.jpg',
      '/693b9092-60cc-448c-87eb-174840743404.jpg',
    ],
    tags: ['4x4', 'China Import', 'Double Cab', 'Petrol'],
    condition: { restored: 20, inspected: 55, original: 25 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
  {
    id: 2,
    category: 'pickup',
    meta: 'Pickup · Ford',
    name: 'Ford Ranger',
    shortName: 'Ranger',
    year: '2022',
    edition: 'Off-Road Edition',
    sku: '#WM-RNG-002',
    origin: 'America',
    transmission: 'Automatic',
    drive: '4x4',
    seats: '5 Seats',
    fuel: 'Petrol',
    power: 'Off-Road Ready',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'Aggressive black Ford Ranger with bold grille, snorkel, and all-terrain setup, built for Ghana’s toughest roads.',
    image: '/5f3b8ce5-c56e-4c70-bd3c-6b82c63f41d6.jpg',
    gallery: [
      '/5f3b8ce5-c56e-4c70-bd3c-6b82c63f41d6.jpg',
      '/818a06be-7b07-403e-809a-a38228abfa9f.jpg',
      '/d8fa383c-5db1-43db-a8f7-8757bb68a026.jpg',
    ],
    tags: ['4x4', 'America Import', 'Snorkel', 'Petrol'],
    condition: { restored: 18, inspected: 58, original: 24 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
  {
    id: 3,
    category: 'pickup',
    meta: 'Pickup · GWM',
    name: 'GWM Poer Off-Road',
    shortName: 'Poer Red',
    year: '2023',
    edition: 'Red Snorkel Edition',
    sku: '#WM-POER-003',
    origin: 'China',
    transmission: 'Automatic',
    drive: '4x4',
    seats: '5 Seats',
    fuel: 'Petrol',
    power: 'Off-Road Spec',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'Striking red GWM Poer with snorkel, black flares, and sports bar, a standout pickup for adventure and utility.',
    image: '/43067f4f-54d3-4156-a097-6de6cb61a56d.jpg',
    gallery: ['/43067f4f-54d3-4156-a097-6de6cb61a56d.jpg'],
    tags: ['4x4', 'China Import', 'Snorkel', 'Double Cab', 'Petrol'],
    condition: { restored: 22, inspected: 50, original: 28 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
  {
    id: 4,
    category: 'pickup',
    meta: 'Pickup · GWM',
    name: 'GWM Poer 4x4',
    shortName: 'Poer Blue',
    year: '2023',
    edition: 'Blue Chrome Edition',
    sku: '#WM-POER-004',
    origin: 'China',
    transmission: 'Automatic',
    drive: '4x4',
    seats: '5 Seats',
    fuel: 'Petrol',
    power: 'Premium Cabin',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'Royal blue GWM Poer 4x4 with chrome grille, bed rack, and premium brown/cream quilted interior.',
    image: '/b8a6241f-c1b2-4dfc-92c9-8047f3f0cafc.jpg',
    gallery: [
      '/b8a6241f-c1b2-4dfc-92c9-8047f3f0cafc.jpg',
      '/5f595e84-d4b2-42bb-a0b5-2d03862f192b.jpg',
      '/63305be3-9062-48a3-b3c1-eb866c39455a.jpg',
      '/3658d2fb-40f3-4cec-b078-3f866dd3aa66.jpg',
    ],
    tags: ['4x4', 'China Import', 'Premium Interior', 'Petrol'],
    condition: { restored: 15, inspected: 60, original: 25 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
  {
    id: 5,
    category: 'pickup',
    meta: 'Pickup · GWM',
    name: 'GWM Poer Bull Bar',
    shortName: 'Poer Bronze',
    year: '2022',
    edition: 'Bronze Utility',
    sku: '#WM-POER-005',
    origin: 'China',
    transmission: 'Automatic',
    drive: '4x4',
    seats: '5 Seats',
    fuel: 'Petrol',
    power: 'Work Ready',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'Bronze metallic GWM Poer with heavy-duty bull bar and LED pods, tough looks for business and transport.',
    image: '/b070a583-6ec1-4bdd-a409-618eb60f1094.jpg',
    gallery: [
      '/b070a583-6ec1-4bdd-a409-618eb60f1094.jpg',
      '/415c4e6d-5853-4732-a002-de7b476d26e0.jpg',
    ],
    tags: ['4x4', 'China Import', 'Bull Bar', 'Petrol'],
    condition: { restored: 25, inspected: 48, original: 27 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
  {
    id: 6,
    category: 'suv',
    meta: 'SUV · Toyota',
    name: 'Toyota Corolla Cross',
    shortName: 'Corolla Cross',
    year: '2024',
    edition: 'White Compact',
    sku: '#WM-CCX-006',
    origin: 'Japan',
    transmission: 'Automatic',
    drive: 'FWD',
    seats: '5 Seats',
    fuel: 'Petrol',
    power: 'City Friendly',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'White Toyota Corolla Cross 2024 compact SUV, efficient, stylish, and ideal for city driving in Ghana.',
    image: '/f1495f19-127c-47c7-97fa-9ec214cc4b52.jpg',
    gallery: [
      '/f1495f19-127c-47c7-97fa-9ec214cc4b52.jpg',
      '/f1495f19-127c-47c7-97fa-9ec214cc4b52-b.jpg',
      '/631c93a4-838d-46f8-bc65-845ae45ba8d4.jpg',
      '/631c93a4-838d-46f8-bc65-845ae45ba8d4-b.jpg',
    ],
    tags: ['SUV', 'Japan Import', 'Compact', 'Petrol'],
    condition: { restored: 12, inspected: 62, original: 26 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
  {
    id: 7,
    category: 'sedan',
    meta: 'Sedan · Toyota',
    name: 'Toyota Vios',
    shortName: 'Vios',
    year: '2021',
    edition: 'White Sedan',
    sku: '#WM-VIO-007',
    origin: 'Japan',
    transmission: 'Automatic',
    drive: 'FWD',
    seats: '5 Seats',
    fuel: 'Petrol',
    power: 'Daily Drive',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'Reliable white Toyota sedan, comfortable, fuel-efficient, and perfect for everyday personal use.',
    image: '/b987da2a-e94c-400e-aaa0-51b7b32ef66b.jpg',
    gallery: [
      '/b987da2a-e94c-400e-aaa0-51b7b32ef66b.jpg',
      '/4ff32133-5011-48bc-963e-0e1363438095.jpg',
    ],
    tags: ['Sedan', 'Japan Import', 'Automatic', 'Petrol'],
    condition: { restored: 20, inspected: 52, original: 28 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
  {
    id: 8,
    category: 'suv',
    meta: 'SUV · Toyota',
    name: 'Toyota RAV4',
    shortName: 'RAV4',
    year: '2022',
    edition: 'White Adventure',
    sku: '#WM-RAV-008',
    origin: 'Japan',
    transmission: 'Automatic',
    drive: 'AWD',
    seats: '5 Seats',
    fuel: 'Petrol',
    power: 'Family SUV',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'Fifth-generation Toyota RAV4 in white, spacious, modern, and trusted for family and highway travel.',
    image: '/acd02303-de0f-4014-b142-461a2ac43ac4.jpg',
    gallery: [
      '/acd02303-de0f-4014-b142-461a2ac43ac4.jpg',
      '/5cb664cf-7729-4527-ae98-72af6a109d87.jpg',
      '/41d0d979-cd65-46e4-89e4-869820932368.jpg',
    ],
    tags: ['SUV', 'Japan Import', 'AWD', 'Petrol'],
    condition: { restored: 14, inspected: 58, original: 28 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
  {
    id: 9,
    category: 'suv',
    meta: 'SUV · Changan',
    name: 'Changan UNI-T',
    shortName: 'UNI-T',
    year: '2023',
    edition: 'Red Sport',
    sku: '#WM-UNI-009',
    origin: 'China',
    transmission: 'Automatic',
    drive: 'FWD',
    seats: '5 Seats',
    fuel: 'Petrol',
    power: 'Modern Crossover',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'Metallic red Changan UNI-T with futuristic grille and red-stitched cabin, bold style for the city.',
    image: '/426076a6-a57b-4b50-85bc-36fe5b046bf5.jpg',
    gallery: [
      '/426076a6-a57b-4b50-85bc-36fe5b046bf5.jpg',
      '/07df2206-6fc8-49cb-a2a1-53b9f086895a.jpg',
      '/e7602ca6-61d7-4a7b-9cad-943528262073.jpg',
    ],
    tags: ['SUV', 'China Import', 'Sport', 'Petrol'],
    condition: { restored: 10, inspected: 65, original: 25 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
  {
    id: 10,
    category: 'suv',
    meta: 'SUV · Jetour',
    name: 'Jetour T2 Traveler',
    shortName: 'Jetour T2',
    year: '2023',
    edition: 'Grey Adventure',
    sku: '#WM-JT2-010',
    origin: 'China',
    transmission: 'Automatic',
    drive: '4x4',
    seats: '5 Seats',
    fuel: 'Petrol',
    power: 'Off-Road SUV',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'Boxy Jetour T2 Traveler with roof box, side ladder, and spare cover, adventure-ready for West Africa.',
    image: '/4c424dee-367a-419c-a349-175e4092f811.jpg',
    gallery: [
      '/4c424dee-367a-419c-a349-175e4092f811.jpg',
      '/cee75be6-9dce-430d-8556-91a739491023.jpg',
    ],
    tags: ['SUV', 'China Import', 'Adventure', '4x4'],
    condition: { restored: 16, inspected: 54, original: 30 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
  {
    id: 11,
    category: 'suv',
    meta: 'SUV · GWM',
    name: 'GWM Tank 300',
    shortName: 'Tank 300',
    year: '2023',
    edition: 'Silver Off-Road',
    sku: '#WM-TNK-011',
    origin: 'China',
    transmission: 'Automatic',
    drive: '4x4',
    seats: '5 Seats',
    fuel: 'Petrol',
    power: 'Rugged SUV',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'Silver GWM Tank 300 with rear spare cover and bold off-road stance, serious capability with premium presence.',
    image: '/70d3244f-9bc4-41e0-80de-a023dceb2d99.jpg',
    gallery: [
      '/70d3244f-9bc4-41e0-80de-a023dceb2d99.jpg',
      '/b5a8afcd-8e0c-46ac-8de7-51bd80b60aed.jpg',
    ],
    tags: ['SUV', 'China Import', '4x4', 'Off-Road'],
    condition: { restored: 18, inspected: 56, original: 26 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
  {
    id: 12,
    category: 'suv',
    meta: 'SUV · Jetour',
    name: 'Jetour Dashing',
    shortName: 'Dashing',
    year: '2023',
    edition: 'Light Grey',
    sku: '#WM-JDS-012',
    origin: 'China',
    transmission: 'Automatic',
    drive: 'FWD',
    seats: '5 Seats',
    fuel: 'Petrol',
    power: 'Family Crossover',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'Light grey Jetour Dashing with panoramic roof and modern styling, comfortable crossover for daily driving.',
    image: '/b7c9c97f-6a00-4c05-96c5-9a3c300d0eae.jpg',
    gallery: [
      '/b7c9c97f-6a00-4c05-96c5-9a3c300d0eae.jpg',
      '/0efea8c3-e88f-4336-9b02-776e682bafbb.jpg',
    ],
    tags: ['SUV', 'China Import', 'Panoramic', 'Petrol'],
    condition: { restored: 12, inspected: 60, original: 28 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
  {
    id: 13,
    category: 'suv',
    meta: 'SUV · Changan',
    name: 'Changan CS Series',
    shortName: 'Changan SUV',
    year: '2022',
    edition: 'Black Premium',
    sku: '#WM-CHS-013',
    origin: 'China',
    transmission: 'Automatic',
    drive: 'FWD',
    seats: '5 Seats',
    fuel: 'Petrol',
    power: 'Premium Cabin',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'Glossy black Changan SUV with honeycomb grille and diamond-stitched interior, refined and ready to drive.',
    image: '/6e0c10ae-fa19-4738-b63e-835a8324334b.jpg',
    gallery: [
      '/6e0c10ae-fa19-4738-b63e-835a8324334b.jpg',
      '/4359e605-65a4-46f5-9997-24b205045dc5.jpg',
    ],
    tags: ['SUV', 'China Import', 'Premium', 'Petrol'],
    condition: { restored: 15, inspected: 57, original: 28 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
  {
    id: 14,
    category: 'suv',
    meta: 'SUV · Haval',
    name: 'Haval H6 GT',
    shortName: 'H6 GT',
    year: '2022',
    edition: 'Black Coupe',
    sku: '#WM-H6G-014',
    origin: 'China',
    transmission: 'Automatic',
    drive: 'FWD',
    seats: '5 Seats',
    fuel: 'Petrol',
    power: 'Sport Crossover',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'Sleek black coupe-style Haval crossover with tinted glass and sporty lines, modern premium SUV styling.',
    image: '/a85eb977-ddc2-4986-9096-ec5dd42ea492.jpg',
    gallery: [
      '/a85eb977-ddc2-4986-9096-ec5dd42ea492.jpg',
      '/811cca07-a850-407a-a292-dff7245babab.jpg',
    ],
    tags: ['SUV', 'China Import', 'Sport', 'Petrol'],
    condition: { restored: 14, inspected: 59, original: 27 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
  {
    id: 15,
    category: 'suv',
    meta: 'SUV · Jetour',
    name: 'Jetour X70',
    shortName: 'X70',
    year: '2022',
    edition: 'White Family',
    sku: '#WM-JX7-015',
    origin: 'China',
    transmission: 'Automatic',
    drive: 'FWD',
    seats: '7 Seats',
    fuel: 'Petrol',
    power: 'Family SUV',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'White Jetour X70 family SUV with chrome grille and connected rear light, spacious option for Ghana families.',
    image: '/6bb8d20d-e0bd-48c9-a093-7978f5469f46.jpg',
    gallery: [
      '/6bb8d20d-e0bd-48c9-a093-7978f5469f46.jpg',
      '/1b92b06d-6746-4bfd-a686-bef7b506d2f7.jpg',
      '/e7d821ec-7371-4786-9f88-a16db81e8e53.jpg',
    ],
    tags: ['SUV', 'China Import', 'Family', 'Petrol'],
    condition: { restored: 17, inspected: 53, original: 30 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
  {
    id: 16,
    category: 'sedan',
    meta: 'Sedan · Toyota',
    name: 'Toyota Levin Hybrid',
    shortName: 'Levin Hybrid',
    year: '2023',
    edition: 'White Hybrid',
    sku: '#WM-LVN-016',
    origin: 'China',
    transmission: 'Automatic',
    drive: 'FWD',
    seats: '5 Seats',
    fuel: 'Hybrid',
    power: 'Fuel Efficient',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'White Toyota Levin Hybrid sedan, modern, efficient, and ideal for city and highway driving across Ghana.',
    image: '/4326cd89-cc68-4d5f-aeff-563d52fc4b64.jpg',
    gallery: [
      '/4326cd89-cc68-4d5f-aeff-563d52fc4b64.jpg',
      '/ff84d59b-0385-4a51-83f1-a4864e6b8c53.jpg',
      '/f1dc6a98-8191-4417-bbf6-2e2278a511a2.jpg',
    ],
    tags: ['Sedan', 'Hybrid', 'China Import', 'Automatic'],
    condition: { restored: 8, inspected: 68, original: 24 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
  {
    id: 17,
    category: 'commercial',
    meta: 'Commercial · Toyota',
    name: 'Toyota Alphard',
    shortName: 'Alphard',
    year: '2018',
    edition: 'White MPV',
    sku: '#WM-ALP-017',
    origin: 'Japan',
    transmission: 'Automatic',
    drive: 'FWD',
    seats: '7 Seats',
    fuel: 'Petrol',
    power: 'Premium MPV',
    location: 'Takoradi',
    priceLabel: 'Enquire for price',
    summary:
      'Spacious white Toyota Alphard MPV, comfortable people-mover for family, business, and passenger transport.',
    image: '/c72b40f3-bf0c-49f3-864c-611be2abaa37.jpg',
    gallery: ['/c72b40f3-bf0c-49f3-864c-611be2abaa37.jpg'],
    tags: ['MPV', 'Japan Import', '7 Seats', 'Commercial'],
    condition: { restored: 30, inspected: 45, original: 25 },
    estimate: 'Enquire',
    checklist: DEFAULT_CHECKLIST,
    services: DEFAULT_SERVICES,
  },
]

export const CAR_FILTERS = [
  { id: 'all', label: 'All' },
  { id: 'pickup', label: 'Pickups' },
  { id: 'suv', label: 'SUVs' },
  { id: 'sedan', label: 'Sedans' },
  { id: 'commercial', label: 'Commercial' },
]

export function getCarById(id) {
  return CARS.find((car) => String(car.id) === String(id))
}
